C *************************************************
C   SUROUTINE JMCONV.FTN
C
C   AUTHOR:  JOANNE MARKHAM
C   DATE:    DEC 1989
C   WRITTEN FOR :  OPTMAIN
C   INTENT:  SPECIAL PURPOSE CONVOLUTION ROUTINE
C    (1)    USES SIMPSON RULE FOR CONVOLUTION
C    (2)    CONVOLUTION IS ONE-SIDED (LAPLACE, NOT FOURIER)
C    (3)    DATA VALUES ARE EQUALLY SPACED
C    (4)    DATA STARTS AT T =0
C    (5)    INCREMENT OF COMPUTED INTEGRAL IS DEL
C    (6)    THE TWO INTEGRANDS HAVE INCREMENT OF DEL/2
C           OR 2* N-1 POINTS INSTEAD OF N
C
C   modify Oct 1992 to make D -output - double precision
C   modify Nov 1992 to make B  input  double precision
C
C   VARIABLE PASSED:    SEE BELOW
C
C
C   CALLED BY:  FUNCTION EVALUATION SUBROUTINES USED BY THE
C               PARAMETER ESTIMATION PROGRAMS (OPTMIZATION PROGRAM)
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
       SUBROUTINE JMCONV (N, DEL, B, G, D)
C
C     N    -  NUMBER OF VALUES IN OUTPUT FUNCTION D
C     DEL  -  INCREMENT FOR OUTPUT FUNCTION D
C     B    -  INTEGRAND WITH 2*N-1 POINTS
C     G    -  INTEGRAND WITH 2*N-1 POINTS
C     D    -  OUTPUT - CONVOLUTION OF B AND G
C
        double precision cona,D,temp,B 
	DIMENSION G(2),B(2),D(2)
       CONA = DBLE(DEL)/6.
       D(1) =0.
       DO 200 I=2,N
       J = 1
       M = 2*I-1
       TEMP=0.
       DO 100 K = 1,I-1
       
       TEMP = TEMP + G(J)*B(M) + 4.0D0*G(J+1)*B(M-1) +
     1       G(J+2)*B(M-2)
       J = J+2
       M = M-2
 100   CONTINUE
       D(I) = CONA*TEMP
 200   CONTINUE
       RETURN
       END
